export const games = [
  {
    id: 1,
    title: "Furious",
    image: "images/games img/cover-furious.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: true,
    hotDeals: false,
    newArrived: false,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Furious is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 2,
    title: "Super Duper",
    image: "images/games img/cover-superduper.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: true,
    hotDeals: false,
    newArrived: false,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Super Duper is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 3,
    title: "Boxer",
    image: "images/games img/cover-boxer.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: true,
    hotDeals: true,
    newArrived: false,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Boxer is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 4,
    title: "Cyberpunk",
    image: "images/games img/cover-cyberpunk.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: true,
    hotDeals: false,
    newArrived: false,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Cyberpunk is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 5,
    title: "Forgelegend",
    image: "images/games img/cover-forgelegend.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: false,
    hotDeals: true,
    newArrived: false,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Forgelegend is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 6,
    title: "Ping Pong",
    image: "images/games img/cover-pingpong.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: false,
    hotDeals: false,
    newArrived: false,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Ping Pong is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 7,
    title: "Racing",
    image: "images/games img/cover-racing.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: false,
    hotDeals: false,
    newArrived: true,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Racing is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 8,
    title: "Space War",
    image: "images/games img/cover-spacewar.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: false,
    hotDeals: false,
    newArrived: true,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Space War is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 9,
    title: "Black",
    image: "images/games img/cover-black.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: false,
    hotDeals: true,
    newArrived: true,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Black is a game where you can challange your ability alone or with friends.",
  },
  {
    id: 10,
    title: "Assassin",
    image: "images/games img/cover-assassins.jpg",
    pXboxOne: true,
    pXbox: true,
    pPs4: true,
    pPs5: true,
    pNintendo: true,
    pPc: true,
    mostSold: false,
    hotDeals: true,
    newArrived: true,
    newPrice: 16,
    usedPrice: 9,
    digitalPrice: 10,
    description:
      "Assassin is a game where you can challange your ability alone or with friends.",
  },
];
